version: 0.2
phases:
  pre_build:
    commands:
      - echo "Checking source code"
      # - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      # - echo COMMIT_HASH = $COMMIT_HASH
      # - echo printenv
      - pip install sqlfluff
      - sqlfluff lint .
  build:
    commands:
      - |
        if [ $CODEBUILD_WEBHOOK_EVENT == 'PUSH' ] ; then
           git fetch origin $CODEBUILD_WEBHOOK_PREV_COMMIT
           DIFF_FILES=$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION $CODEBUILD_WEBHOOK_PREV_COMMIT)
           echo DIFF_FILES = $DIFF_FILES
           git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION $CODEBUILD_WEBHOOK_PREV_COMMIT | grep "sql/.*sql" | xargs -I{} echo "run --filename {}"
        fi
